spring:
    application:
        name: spring-boot-template

    config:
        import: optional:file:.env[.properties]

    datasource:
        url: jdbc:postgresql://localhost:5432/documents
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

minio:
    user: ${MINIO_USER}
    password: ${MINIO_PASSWORD}
    bucket: ${MINIO_BUCKET:documents}
